# Site settings
title: matrix
email: admin@matrix.ac
description: > # this means to ignore newlines until "baseurl:"
  The matrix is a network of machines providing access to a Unix-like shell and services.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://matrix.ac" # the base hostname & protocol for your site
twitter_username: matrix_ac
github_username:  matrix-ac

nav:
- page: join
  permalink: /join

- page: docs
  permalink: /docs

- page: blog
  permalink: /blog

docs-list: [Chat, Web Publishing, Command Line, VPN]

# Build settings
markdown: kramdown
