# Site settings
title: matrix
email: admin@matrix.ac
description: > # this means to ignore newlines until "baseurl:"
  The matrix is a network of machines giving university students access to a Unix shell and services.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matrix.ac" # the base hostname & protocol for your site
twitter_username: matrix_ac
github_username:  matrix-ac

nav:
- page: join us
  permalink: /join

- page: zion archive
  permalink: /zion-archive

- page: blog
  permalink: /blog

zion-list: [Chat, Web Publishing, Command Line]

# Build settings
markdown: kramdown
